### ISSUE TITLE
Is there any reason to no integrate this in the ocamlbuild project ? 

### ISSUE THREAD

**Issue by dbuenzli** [gasche/manual-ocamlbuild#32]
and can I get a stable URL before I start linking to it ?

**Comment by gasche** [comment]
The bad reason is that it feels a bit too drafty right now to go in the "official" documentation. The good reason is that I did not take the time to do it yet.

I would like to take the opportunity to turn it into an AsciiDoc document, to get the nice table-of-contents generation and generally better features (and worse syntax), but if someone beats me to it and just submits a simple pull-request for inclusion in the right place I won't complain.

What would a good stable URL be for this? A github.io page in the ocamlbuild project? Would we have to write a Makefile to do the actual rendering, then, or does Github support rendering on their side for those pages as well?

**Comment by dbuenzli** [comment]
> The bad reason is that it feels a bit too drafty right now to go in the "official" documentation. The good reason is that I did not take the time to do it yet.

Ok. But it describes a few things, e.g. ocamlfind packages that are not described in the official docs. 


> What would a good stable URL be for this? A github.io page in the ocamlbuild project?

Sounds reasonable. 

> Would we have to write a Makefile to do the actual rendering, then, or does Github support rendering on their side for those pages as well?

No idea. But I'd suggest to do the rendering yourself, [here's a script](https://github.com/ocaml/ocamlunix/blob/master/publish-gh) that automates the publication of a bunch of files on github pages which shouldn't be too hard to adapt.

**Comment by sanmai-NL** [comment]
My two cents before you commence rewriting the documentation in another markup format. What about [Pandoc Markdown](http://pandoc.org/README.html) vs. [AsciiDoc(tor)](http://asciidoctor.org/docs/asciidoc-asciidoctor-diffs/)? The latter does not support e.g. citations, as far as I know. The former is better supported by the well-maintained and feature-complete Pandoc tooling. AsciiDoc(tor) has a more natural and elegant syntax than Markdown, IMO. Also, AsciiDoctor has very good macro-like features, e.g. file snippet inclusion.

**Comment by gasche** [comment]
During the writing of this manual I saw value in the fact that it was rendered directly on its github page. Once it is released, it may have a rendered static version, which makes the issue less important, but the reason I considered AsciiDoc above is that github renders it (this idea was given to me by @c-cube which did a similar transformation on the compiler's INSTALL and README files).

I'm a pandoc fan (I like using good tools written in good languages) and use it for my personal documents, but I feel that a well-documented and standardized format would be the better choice here. (I'm not fond of the AsciiDoc syntax which felt sensibly heavier than Markdown's to me, but I'm fine with using it still).

@sanmai-NL, if you were interested in contributing the translation to the AsciiDoc format (which you seem more familiar with), that could be very nice!

**Comment by sanmai-NL** [comment]
Rendering the ToC from an AsciiDoctor document on directly on GitHub did not work for me in [this document](https://github.com/clarin-eric/SPF-tutorial/blob/master/Shib_SP_tutorial.adoc) (also a helpful example of how to use the various AsciiDoctor features). As a workaround I rendered the document to HTML and put that in the repo alongside the AsciiDoc source, and then linked to from a GitHub CDN. See https://github.com/clarin-eric/SPF-tutorial/blob/master/README.adoc. But I strongly favor Daniel Bünzli's GitHub pages solution instead.

I'd enjoy helping out, but I do not have much time either. If the documentation work is clearly specified and broken down, I can take up one such ticket.

**Comment by c-cube** [comment]
For qtest's readme, I had something like this:

:toc: macro
:toclevels: 4

to make the toc work properly.

**Comment by sanmai-NL** [comment]
@gasche: Good news, I've completely rewritten the manual in Asciidoctor. The results are very good, the document has become far easier to maintain and rewad. Could you quickly make an `Asciidoctor` branch on this repo this repo that I can push to, in one big commit? Or perhaps one in the `ocamlbuild` repo itself?

**Comment by gasche** [comment]
You could send a PR here to completely replace the markdown version of the manual (in master). The short-term plan is indeed to put the manual in ocamlbuild, but we can do this in two steps, first convert here and then move to there. Thanks for your help!

**Comment by sanmai-NL** [comment]
See PR #34.

**Comment by william3** [comment]
To comment on the initial question, I think this manual is already very nice, and should improve with time, so I would not consider it as a draft.

**Comment by gasche** [comment]
I sent a PR to integrate this manual in the ocamlbuild repository: ocaml/ocamlbuild#78

**Comment by dbuenzli** [comment]
What's the stable URL I should link to then ?

**Comment by sanmai-NL** [comment]
@dbuenzli: Based on what I know, an URL into the relevant GitHub repository (e.g., current version on master branch). If my new PR #35 is merged, every (`ocamlbuild`) release on GitHub is to recieve an HTML and PDF attachment with the manual, which you could link to as well.

**Comment by dbuenzli** [comment]
> Based on what I know, an URL into the relevant GitHub repository (e.g., current revision on master branch).

That's not what I call a stable URL.

**Comment by sanmai-NL** [comment]
I see that point, but I do not know about the possibilities outside that. What specific threats to the URL availability and persistence do you have in mind? Could an actively maintained redirect from a stable website such as ocaml.org be a solution?

**Comment by dbuenzli** [comment]
Le lundi, 2 mai 2016 à 11:08, Sander Maijers a écrit :

> I see that point, but I do not know about the possibilities outside that. What specific threats to the URL availability and persistence do you have in mind? Could an actively maintained redirect from a stable website such as ocaml.org (http://ocaml.org) be a solution?

A publication on github.io would be fine. Just an URL that is vaguely user friendly, not tied to the current repository structure and agnostic to the current publication format.  

Daniel

**Comment by gasche** [comment]
So the merge is done in the [ocamlbuild repository](https://github.com/ocaml/ocamlbuild/), see [ocamlbuild/manual/manual.adoc](https://github.com/ocaml/ocamlbuild/blob/master/manual/manual.adoc). I need to wrap up the present repository by merging or porting remaining PRs, and solving or porting remaining issues.
