### ISSUE TITLE
list of available tags

### ISSUE THREAD

**Issue by nilsbecker** [gasche/manual-ocamlbuild#8]
just as a general feedback on what i found missing in the ocamlbuild documentation personally: i wanted to quickly write a `_tags` file to state the necessary packages and maybe to switch between debugging builds and regular ones. i remember being frustrated at not finding a good quick overview of all available tags in a prominent place. it would be good to have that.

**Comment by gasche** [comment]
Thanks, that is very useful feedback. Note that you can use `ocamlbuild -documentation` to have a list of the non-parametrized tags the tool knows about (it will also tell you about the tags installed locally by `myocamlbuild.ml`, which is useful). It does not work for parametrized tags (and I'm not quite sure how to solve that), so a centralized listing would still be useful.

**Comment by gasche** [comment]
I think that the [Tags](https://github.com/gasche/manual-ocamlbuild/blob/master/manual.md#reference-tags) reference documentation now solves this problem. Of course, with user-defined plugins, there may be many other tags available to a given project, which still makes `ocamlbuild -documentation` more useful.
